title: "Evaluation of Latent Friction Ridge Technology (ELFT)"
description: "Supplemental information regarding NIST's Evaluation of Latent Friction Ridge Technology"
baseurl: "/elft"
rooturl: "https://pages.nist.gov"
